### PR TITLE
add x-engine compatibility by dropping ES5 isArray and switching to toString

### PR DESCRIPTION
**Pull request by wilmoore**
This switches to using `Object.prototype.toString.call(...) === '[object Array]'` instead of `Array.isArray(...)` since the former allows this to work in older browsers without shims/polyfills.

As an aside, this also adds `mocha` to `devDependencies` so contributors don't necessarily have to have mocha installed globally.

### CODE REVIEW

**Comment by jonschlinkert** [comment]
thanks for the pr, but I'd rather this library be as performant and idiomatic as possible for node.js usage.  On average, calling `toString` on the `Object` prototype will be 10x slower (literally) than using `Array.isArray`. 

With all of that said, I do really appreciate the pr, the time you have taken out of your own day and thoughtfulness of wanting to help me improve this library. I can look around for other libraries that can meet your needs if that helps. 

also I can merge in the mocha changes if you want, but it sounds like you might not even be able to use this without your changes. I'll leave that to you. thank you!

**Comment by wilmoore** [comment]
No worries man, thanks anyhow :+1:

**Comment by wilmoore** [comment]
Just as a heads-up, I did go ahead and create what I was looking for as I couldn't find it anywhere on npm. Pretty much all the other options used the same method as you do here.

Thanks again though.

**Comment by jonschlinkert** [comment]
:+1:

**Pull request closed without merging**
